### ISSUE TITLE
Module not found after installing PyWin32

### ISSUE THREAD

**Issue by RiSNFoX** [LagoLunatic/wwrando#97] opened 2019-01-18 08:24 UTC
Randomizer not starting after installing PyWin32, which I use for a music bot I made.
It works just fine if it's not installed.

```
Traceback (most recent call last):
  File ".\wwrando.py", line 9, in <module>
    from ui.randomizer_window import WWRandomizerWindow
ImportError: DLL load failed: The specified module could not be found.
```
EDIT: I fixed it for myself by simply renaming the folder to "ww_ui" and replacing that whenever it imported "ui.*"

**Comment by LagoLunatic** [comment] 2019-01-18 17:36
I installed pywin32 and couldn't reproduce this issue.

I have no idea why renaming a folder would fix the issue for you. But since you say it's resolved I'll close this issue.

**Closed by LagoLunatic** 2019-01-18 17:36 UTC

**Comment by RiSNFoX** [comment] 2019-01-18 23:47
Could you have installed it with the same python version you were using for the randomizer?
I'm not that good at python so I have no idea if that matters at all or not. But yeah after changing the folder name and the .py files to match the folder it worked with Pywin32 installed

**Comment by LagoLunatic** [comment] 2019-01-18 23:55
>Could you have installed it with the same python version you were using for the randomizer?

Yeah I made sure to use the pip associated with the same python version I use to run the rando.

Your error message suggests that there's some DLL needed by randomizer_window.py which can't be found (though it doesn't say which). If that's the case it's pretty bizarre that simply renaming the folder randomizer_window.py is in would make the DLL suddenly be found.

**Comment by RiSNFoX** [comment] 2019-01-19 00:37
Is there any way I could get a more detailed description of the message it sends me? I'd be willing to see if it's an actual fault or just a thing in my system that's broken

**Comment by LagoLunatic** [comment] 2019-01-19 01:01
I don't know of any way to get a better error message.

Only thing I can think of to test is try deleting or commenting out lines 11 through 21 of wwrando.py and see if it runs. The code in that section is the only code in the whole program that deals with windows systems calls or DLLs or anything, so if there's an issue in the randomizer's code, I think it would be within those lines.

But your error message happens on line 9 of wwrando.py, so it seems pretty unlikely that something *after* that would be causing the error.

**Comment by RiSNFoX** [comment] 2019-01-19 02:18
Yeah, I've just tested that and it didn't change anything. No idea what could be causing it. Could it be any other packages I have installed?

**Comment by LagoLunatic** [comment] 2019-01-19 02:21
I wouldn't know how some other library causes this any more than I know how PyWin32 causes it. You can try uninstalling any libraries you have that you don't need if you want.

**Comment by RiSNFoX** [comment] 2019-01-19 04:16
Okay, I've done some testing with the uninstalling, it seems it wasn't pywin32, but win32core. Could you see if installing that on your end gives you the error it was throwing me?

**Comment by LagoLunatic** [comment] 2019-01-19 23:20
After installing win32gui I do finally get the error. It's strange though, since if I `import win32gui` it imports that module normally. But if I `import ui` while win32gui is installed, it has a DLL error. Seems like a bug in win32gui.

I renamed the ui folder in dc51e1bfcac39619d4aa767a65390897e2542e08. Hopefully there aren't any other modules with conflicting names of folders.
