### ISSUE TITLE
Damage Multiplier?

### ISSUE THREAD

**Issue by Justmax98** [LagoLunatic/wwrando#345] opened 2023-08-24 17:30 UTC
In the oot and mm randomizer there was a damage multiplier, in this one I can't find one which is annoying because wind waker has the easiest combat ever making half the game really boring

**Comment by wooferzfg** [comment] 2023-08-24 17:32
https://github.com/LagoLunatic/wwrando/issues/67#issuecomment-609643517

**Comment by Justmax98** [comment] 2023-08-24 17:43
> [#67 (comment)](https://github.com/LagoLunatic/wwrando/issues/67#issuecomment-609643517)

*facepalm* dolphin turns off ar cheats on randomizers, in fact I tested that on the regular game and it didn't even work, any other suggestions?

**Comment by wooferzfg** [comment] 2023-08-24 17:46
> dolphin turns off ar cheats on randomizers

This isn't true. You're probably doing something wrong, maybe try asking for help in the Discord?

**Comment by Justmax98** [comment] 2023-08-24 17:59
> > dolphin turns off ar cheats on randomizers
> 
> This isn't true. You're probably doing something wrong, maybe try asking for help in the Discord?

UPDATE: I found the enable cheats check, at first I thought it wasn't working because I set it to 02 for 2x like I did oot and mm and enemies were still only taking a quarter of a heart, but then I remembered the dyk gaming story where just because one sloppy tester died on the first boss they decided to make the damage done by enemies even less than the last two games so I have to set it around 4x or 6x for the game to have even a hint of difficulty when it comes to combat and enemies. The designers really dropped the ball there because I have been playing this since I was 8 and never died once where as every other I did at least  3 or 4 times and I guess in general this randomizer should already have a damage multiplier in the first place since ootr and mmr do and this is clearly the easiest zelda damage/combat wise

**Comment by LagoLunatic** [comment] 2023-08-24 19:21
Duplicate of #67

**Closed by LagoLunatic** 2023-08-24 19:21 UTC
